### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

In [ ]:
import numpy as np

#####1.  Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [5]:
import numpy as np

array_of_zeros = np.zeros(10)
print("Array of 10 zeros:")
print(array_of_zeros)

array_of_ones = np.ones(10)
print("\nArray of 10 ones:")
print(array_of_ones)

array_of_fives = np.ones(10) * 5
print("\nArray of 10 fives:")
print(array_of_fives)


Array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
## sample output

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#####2.  Write a NumPy program to create an array of the integers from 30 to 70.

In [2]:
array_of_integers = np.arange(30, 71)
print("Array of integers from 30 to 70:")
print(array_of_integers)

Array of integers from 30 to 70:
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [ ]:
### sample output

Array of the integers from 30 to70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


######3. Write a NumPy program to create an array of all the even integers from 10 to 50.

In [12]:
even_integers_array = np.arange(10, 50, 2)
print("Array of even integers from 10 to 50:")
print(even_integers_array)


Array of even integers from 10 to 50:
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [ ]:
## sample output


Array of all the even integers from 10 to 50
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


######4. Write a NumPy program to create a 3x3 identity matrix.

In [11]:
identity_matrix = np.identity(3)
print("3x3 Identity Matrix:")
print(identity_matrix)

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
## sample output

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##### 5. Write a NumPy program to generate a random number between 0 and 1

In [13]:
random_number = np.random.rand()
print("Random number between 0 and 1:")
print(random_number)

Random number between 0 and 1:
0.09719883303171428


In [ ]:
## sample output

Random number between 0 and 1:
[0.40400053]


###### 6. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [15]:
random_numbers = np.random.randn(15)
print("Array of 15 random numbers from a standard normal distribution:")
print(random_numbers)

Array of 15 random numbers from a standard normal distribution:
[ 0.13432587 -0.71419781  0.46167711  0.38471628 -1.35313687  1.39920404
  0.60236412  0.21498036  0.61577752 -1.44190334  0.50804306 -0.75304409
 -0.31350885 -0.37274573  0.28055297]


In [ ]:
## sample output

15 random numbers from a standard normal distribution:
[ 0.68439314  1.50916987 -0.75364839  0.1038106   0.07789927 -0.15349755
  1.78151615  0.49989426  0.18791322 -1.51931266 -0.55512066  2.02808972
  0.37648568  0.57999878 -0.31095957]


###### 7. Write a NumPy program to create a 3X4 array using and iterate over it.

In [ ]:
## code here


In [ ]:
## sample output

Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 

###### 8. Write a NumPy program to multiply the values ​​of two given vectors.

In [17]:
## code here

vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

result_multiply = np.multiply(vector1, vector2)
print("Result using np.multiply():", result_multiply)



Result using np.multiply(): [ 4 10 18]


In [ ]:
## sample output

Vector-1
[1 8 3 5]
Vector-2
[10  1  4 10]
Multiply the values of two said vectors:
[10  8 12 50]


###### 9. Write a NumPy program to reverse an array (first element becomes last).

In [19]:
### code here

original_array = np.array([1, 2, 3, 4, 5,6,7,8,9,10])

reversed_array = np.flip(original_array)

print("Original Array:", original_array)
print("Reversed Array:", reversed_array)


Original Array: [ 1  2  3  4  5  6  7  8  9 10]
Reversed Array: [10  9  8  7  6  5  4  3  2  1]


In [1]:
## sample output

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


##### 10. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [20]:
## code here

zero_matrix = np.zeros((5, 5))
np.fill_diagonal(zero_matrix, [1, 2, 3, 4, 5])

print("5x5 Zero Matrix with Main Diagonal Elements:")
print(zero_matrix)


5x5 Zero Matrix with Main Diagonal Elements:
[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


In [ ]:
## sample output

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


###### 11. Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.

In [25]:
## code here

import numpy as np

sample_array = np.array([[1, 2],
                         [3,4]])

total_sum = np.sum(sample_array)
print("Sum of all elements:", total_sum)


column_sums = np.sum(sample_array, axis=0)
print("Sum of each column:")
print(column_sums)

row_sums = np.sum(sample_array, axis=1)
print("\nSum of each row:")
print(row_sums)


Sum of all elements: 10
Sum of each column:
[4 6]

Sum of each row:
[3 7]


In [ ]:
##### 

In [ ]:
## sample output

Original array:
[[0 1]
 [2 3]]
Sum of all elements:
6
Sum of each column:
[2 4]
Sum of each row:
[1 5]


###### 12. Write a NumPy program to compute the inner product of two given vectors.

In [23]:

import numpy as np

vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])



In [ ]:
## sample output

Original vectors:
[4 5]
[ 7 10]
Inner product of said vectors:
78
